# Generated by Django 4.1.3 on 2022-11-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signUpInfo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginUser', models.CharField(max_length=122)),
                ('loginPassword', models.CharField(max_length=122)),
                ('rePassword', models.CharField(max_length=122)),
            ],
        ),
    ]
