# Generated by Django 4.1.3 on 2022-11-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signUpInfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=122)),
                ('lastName', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('otp', models.CharField(max_length=122)),
                ('document', models.FileField(upload_to=None)),
            ],
        ),
    ]
