# Generated by Django 4.1.3 on 2022-11-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_signupinfo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupinfo2',
            name='document',
        ),
    ]
