# Generated by Django 4.1.3 on 2022-11-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_signupinfo2_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=122)),
                ('lastName', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('loginPassword', models.CharField(max_length=122)),
                ('otp', models.CharField(max_length=122)),
                ('document', models.FileField(null=True, upload_to=None)),
            ],
        ),
        migrations.DeleteModel(
            name='signUpInfo1',
        ),
        migrations.DeleteModel(
            name='signUpInfo2',
        ),
    ]
