# Generated by Django 4.1.3 on 2022-11-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_userinfo_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='document',
            field=models.FileField(null=True, upload_to='static/upload'),
        ),
    ]
