# Generated by Django 4.1.3 on 2022-11-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_userinfo_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='document',
            field=models.FileField(null=True, upload_to='static/uploads/<django.db.models.fields.EmailField>'),
        ),
    ]
