# Generated by Django 4.1.3 on 2022-11-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_doctorinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='document',
            field=models.FileField(null=True, upload_to='static/uploads/<django.db.models.fields.EmailField>'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='uploaded_image1',
            field=models.FileField(null=True, upload_to='static/uploads/<django.db.models.fields.EmailField>'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='uploaded_image2',
            field=models.FileField(null=True, upload_to='static/uploads/<django.db.models.fields.EmailField>'),
        ),
    ]
