# Generated by Django 4.1.3 on 2022-11-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_doctorinfo_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=122)),
                ('lastName', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('loginPassword', models.CharField(max_length=122)),
                ('uniqueID', models.CharField(max_length=122)),
                ('phoneNumber', models.CharField(max_length=122)),
                ('uploaded_image1', models.FileField(null=True, upload_to='static/uploads/<django.db.models.fields.EmailField>')),
                ('uploaded_image2', models.FileField(null=True, upload_to='static/uploads/<django.db.models.fields.EmailField>')),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=122)),
                ('lastName', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('loginPassword', models.CharField(max_length=122)),
                ('uploaded_image1', models.FileField(null=True, upload_to='static/uploads/<django.db.models.fields.EmailField>')),
                ('uploaded_image2', models.FileField(null=True, upload_to='static/uploads/<django.db.models.fields.EmailField>')),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=122)),
                ('lastName', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('loginPassword', models.CharField(max_length=122)),
                ('uniqueID', models.CharField(max_length=122)),
                ('phoneNumber', models.CharField(max_length=122)),
                ('uploaded_image1', models.FileField(null=True, upload_to='static/uploads/<django.db.models.fields.EmailField>')),
                ('uploaded_image2', models.FileField(null=True, upload_to='static/uploads/<django.db.models.fields.EmailField>')),
            ],
        ),
        migrations.DeleteModel(
            name='doctorInfo',
        ),
        migrations.DeleteModel(
            name='userInfo',
        ),
    ]
