# Generated by Django 4.1.3 on 2022-11-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_doctor_organization_patient_delete_doctorinfo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctor',
            new_name='healthcare_professional',
        ),
    ]
