# Generated by Django 4.1.3 on 2022-11-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_booked_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_appointment',
            name='time',
            field=models.CharField(max_length=122),
        ),
    ]
