# Generated by Django 4.1.3 on 2022-11-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_booked_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_appointment',
            name='time',
            field=models.TimeField(max_length=122),
        ),
    ]
