# Generated by Django 4.1.3 on 2022-11-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_booked_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=122),
        ),
        migrations.AddField(
            model_name='organization',
            name='uniqueID',
            field=models.CharField(default=None, max_length=122),
        ),
    ]
