# Generated by Django 3.2.16 on 2022-11-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_organization_phonenumber_organization_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcare_professional',
            name='email',
            field=models.EmailField(max_length=122, unique=True),
        ),
        migrations.AlterField(
            model_name='healthcare_professional',
            name='phoneNumber',
            field=models.CharField(max_length=122, unique=True),
        ),
        migrations.AlterField(
            model_name='healthcare_professional',
            name='uniqueID',
            field=models.CharField(max_length=122, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=122, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=122, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='uniqueID',
            field=models.CharField(default=None, max_length=122, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=122, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phoneNumber',
            field=models.CharField(max_length=122, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='uniqueID',
            field=models.CharField(max_length=122, unique=True),
        ),
    ]
